name: ci_spdx_license_header_check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  check_license_header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Check SPDX Licenses
        uses: to-sta/spdx-checker-action@v0.0.3
        with:
          target-license: "BSD-3-Clause"
          file-paths: "**/*.py"
          extensions: "py"
          exclude: "dist/,**/*.md,**/*.txt,**/.git/**,**/*__init__.py"
          continue-on-error: false
          fix: false
